services:
  - type: web
    name: lawn-peak-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 10000

  - type: web
    name: lawn-peak-front
    env: python
    buildCommand: |
      npm install
      npm run build
      pip install -r requirements.txt
    startCommand: gunicorn frontend:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PORT
        value: 10000
      - key: API_URL
        value: https://lawn-peak-api.onrender.com
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
